### ISSUE TITLE
Do we need an Item Service page?

### ISSUE THREAD

**Issue by Edwards97** [CSCE-546-FantasyL/FantasyL#5]
Are we using an Item.Service page thing or are we coordinating our firebase a different way?
If yes to Item.Service, who is heading that up?
Same question to who is heading up the different method?

**Comment by sem15** [comment]
I'm not sure what other options exist, but if we choose to use a service I think the main question is whether we use one central service or multiple services for each different entity ie: Players, Leagues, etc...

**Comment by Edwards97** [comment]
My vote is for the item.service because its familiar, but I wanted to ask first before talking about who wants to head that up. Thoughts? @DopaiHub

**Comment by sem15** [comment]
Regardless of what we choose I don't mind taking it

**Comment by DopaiHub** [comment]
We'll have to make a service, for the homeworks for class order service and items service was used. So in this case It'd prob be best to make a player/roster service(?) and a league service.
